### ISSUE TITLE
Design UI elements

### ISSUE THREAD

**Issue by jafrilli** [acm-projects/hashpost#5]
Along with working with API data, designing our app with a clean ass user interface is essential to making a great application, along with maintaining our project manager's reputation of being UTD's most artsy nerd. In order to have an edge over our competitors, we need to go all out on the design. And what better way to do so than to add A N I M A T I O N S.

We'll be using:
- InVision Studio (for static .svg assets)
- Flare by 2Dimensions (for animations)

Flutter partnered up with Flare to make it easy for developers to integrate awesome animations into their apps. And we'll be taking advantage of that (hopefully).
https://www.2dimensions.com/about-flare

**Comment by WillieCubed** [comment]
Question: why is this a stretch goal? I think the app should have polish because that's what @beaagron expects of us. 😉.

Comment: I love animations. I think we should consider the Material Design guidelines for [animation](https://material.io/design/motion/understanding-motion.html#principles) as they're very fluid intuitive. Also, Flare looks absolutely amazing at making custom animations.

**Comment by jafrilli** [comment]
I thought stretch goals are goals that aren't listed in the MVP.
